<a href="https://colab.research.google.com/github/junpito/collections-of-college-task/blob/main/Tugas_Praktikum_AI_2_Kelompok_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
from google.colab import drive
drive.mount('/content/gdrive')

Mounted at /content/gdrive


In [ ]:
df = pd.read_csv("/content/gdrive/MyDrive/praktikum/heart.csv")
df.head()


age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  slope  \
0   52    1   0       125   212    0        1      168      0      1.0      2   
1   53    1   0       140   203    1        0      155      1      3.1      0   
2   70    1   0       145   174    0        1      125      1      2.6      0   
3   61    1   0       148   203    0        1      161      0      0.0      2   
4   62    0   0       138   294    1        1      106      0      1.9      1   

   ca  thal  target  
0   2     3       0  
1   0     3       0  
2   0     3       0  
3   1     3       0  
4   3     2       0

In [ ]:
df = df.to_numpy()

In [ ]:
df

array([[52.,  1.,  0., ...,  2.,  3.,  0.],
       [53.,  1.,  0., ...,  0.,  3.,  0.],
       [70.,  1.,  0., ...,  0.,  3.,  0.],
       ...,
       [47.,  1.,  0., ...,  1.,  2.,  0.],
       [50.,  0.,  0., ...,  0.,  2.,  1.],
       [54.,  1.,  0., ...,  1.,  3.,  0.]])

In [ ]:
dataTraining = np.concatenate((df[0:40, :], df[50:90, :]),
                              axis=0)
dataTesting = np.concatenate((df[40:50, :], df[90:100, :]),
                                axis=0)



In [ ]:
print(dataTraining)
len(dataTraining)

[[52.  1.  0. ...  2.  3.  0.]
 [53.  1.  0. ...  0.  3.  0.]
 [70.  1.  0. ...  0.  3.  0.]
 ...
 [59.  0.  0. ...  0.  2.  0.]
 [62.  0.  0. ...  2.  2.  0.]
 [68.  1.  0. ...  2.  3.  0.]]


80

In [ ]:
print(dataTesting)
len(dataTesting)

[[6.50e+01 0.00e+00 2.00e+00 1.60e+02 3.60e+02 0.00e+00 0.00e+00 1.51e+02
  0.00e+00 8.00e-01 2.00e+00 0.00e+00 2.00e+00 1.00e+00]
 [5.40e+01 1.00e+00 2.00e+00 1.20e+02 2.58e+02 0.00e+00 0.00e+00 1.47e+02
  0.00e+00 4.00e-01 1.00e+00 0.00e+00 3.00e+00 1.00e+00]
 [6.10e+01 0.00e+00 0.00e+00 1.30e+02 3.30e+02 0.00e+00 0.00e+00 1.69e+02
  0.00e+00 0.00e+00 2.00e+00 0.00e+00 2.00e+00 0.00e+00]
 [4.60e+01 1.00e+00 0.00e+00 1.20e+02 2.49e+02 0.00e+00 0.00e+00 1.44e+02
  0.00e+00 8.00e-01 2.00e+00 0.00e+00 3.00e+00 0.00e+00]
 [5.50e+01 0.00e+00 1.00e+00 1.32e+02 3.42e+02 0.00e+00 1.00e+00 1.66e+02
  0.00e+00 1.20e+00 2.00e+00 0.00e+00 2.00e+00 1.00e+00]
 [4.20e+01 1.00e+00 0.00e+00 1.40e+02 2.26e+02 0.00e+00 1.00e+00 1.78e+02
  0.00e+00 0.00e+00 2.00e+00 0.00e+00 2.00e+00 1.00e+00]
 [4.10e+01 1.00e+00 1.00e+00 1.35e+02 2.03e+02 0.00e+00 1.00e+00 1.32e+02
  0.00e+00 0.00e+00 1.00e+00 0.00e+00 1.00e+00 1.00e+00]
 [6.60e+01 0.00e+00 0.00e+00 1.78e+02 2.28e+02 1.00e+00 1.00e+00 1.65e+02
  1.00e+0

20

In [ ]:
inputTraining = dataTraining[:, 0:4]
inputTesting = dataTesting[:, 0:4]
labelTraining = dataTraining[:, 4]
labelTesting = dataTesting[:, 4]
print(labelTraining)
len(labelTraining)

[212. 203. 174. 203. 294. 248. 318. 289. 249. 286. 149. 341. 210. 298.
 204. 210. 308. 266. 244. 211. 185. 223. 208. 252. 209. 307. 233. 319.
 256. 327. 169. 244. 131. 269. 196. 231. 213. 271. 263. 229. 283. 241.
 175. 188. 217. 217. 193. 245. 212. 232. 204. 278. 299. 212. 204. 288.
 197. 315. 215. 164. 326. 207. 249. 177. 256. 257. 255. 187. 201. 201.
 233. 149. 231. 175. 215. 220. 211. 249. 268. 193.]


80

In [ ]:
from sklearn import tree
model = tree.DecisionTreeClassifier()

In [ ]:
model = model.fit(inputTraining, labelTraining)

In [ ]:


hasilPrediksi = model.predict(inputTesting)
print("Label Sebenarnya : ", labelTesting)
print("Hasil Prediksi : ", hasilPrediksi)



Label Sebenarnya :  [360. 258. 330. 249. 342. 226. 203. 228. 278. 230. 267. 209. 187. 169.
 208. 236. 303. 282. 248. 197.]
Hasil Prediksi :  [269. 197. 294. 249. 217. 315. 315. 164. 278. 318. 248. 294. 187. 169.
 263. 341. 241. 286. 318. 185.]


In [ ]:
import matplotlib.pyplot as plt

In [ ]:


prediksiBenar = (hasilPrediksi == labelTesting).sum()
prediksiSalah = (hasilPrediksi != labelTesting).sum()
print("Prediksi Benar : ", prediksiBenar, "data")
print("Prediksi Salah : ", prediksiSalah, "data")
print("Akurasi :", prediksiBenar/(prediksiBenar+prediksiSalah) * 100, "%")



Prediksi Benar :  4 data
Prediksi Salah :  16 data
Akurasi : 20.0 %
